using System;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class InformationCategory {

    [Header("Category")]
    [SerializeField] private string categoryName;
    [SerializeField] private List<string> information;

    // for custom categories that are generated by script
    public InformationCategory(string categoryName, List<string> information) {

        this.categoryName = categoryName;
        this.information = information;

    }

    public string GetCategoryName() { return categoryName; }

    public string GetRandomInformation() { return information[UnityEngine.Random.Range(0, information.Count)]; }

}
